version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - run: npm run release

  deploy-beta:
    docker:
      - image: circleci/node:12.14
    environment:
      AWS_REGION: us-west-2
    steps:
      - checkout
      - run: npm run release
      - run: AWS_ACCESS_KEY_ID=$BETA_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$BETA_AWS_SECRET_ACCESS_KEY npm run deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy-beta:
          filters:
            branches:
              only: master